//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/_Scripts/_Input/BasicControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @BasicControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @BasicControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BasicControls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""d43f1f2f-86a2-44c4-aeff-564bff731131"",
            ""actions"": [
                {
                    ""name"": ""StickRight"",
                    ""type"": ""Value"",
                    ""id"": ""0fa21c14-e7f5-41c7-b325-8a2ec38ebeb1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StickLeft"",
                    ""type"": ""Value"",
                    ""id"": ""da14c616-ecbf-4871-a9bf-d7ac93725e5e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StickButtonRight"",
                    ""type"": ""Button"",
                    ""id"": ""258fb52f-9f70-4978-bf9a-372547861cbf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StickButtonLeft"",
                    ""type"": ""Button"",
                    ""id"": ""4a62edff-b05a-4b14-b975-21b6da26fc13"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowUp"",
                    ""type"": ""Button"",
                    ""id"": ""80c84240-95f9-43b8-83da-43e3771b6729"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowDown"",
                    ""type"": ""Button"",
                    ""id"": ""f765fc6d-3e9f-40c1-89bb-db9af6a3a021"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowLeft"",
                    ""type"": ""Button"",
                    ""id"": ""d2882894-50db-415d-ab9d-2c1145133d77"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArrowRight"",
                    ""type"": ""Button"",
                    ""id"": ""ec05d8e3-c080-4820-b195-11dfcefe27b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonNorth"",
                    ""type"": ""Button"",
                    ""id"": ""c1544e96-f668-4202-880c-cda58f5eafce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonSouth"",
                    ""type"": ""Button"",
                    ""id"": ""98a5405e-61d8-4cf1-abdd-f449afbf55a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonEast"",
                    ""type"": ""Button"",
                    ""id"": ""0627f2f0-a70c-4b61-b33d-0f5b55ba4701"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ButtonWest"",
                    ""type"": ""Button"",
                    ""id"": ""1fe6c057-d0a8-4b4c-9f77-b24e3ac906ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShoulderLeft"",
                    ""type"": ""Button"",
                    ""id"": ""1c96bf0e-7a4f-419e-84d8-9d92c4917925"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShoulderRight"",
                    ""type"": ""Button"",
                    ""id"": ""bd33ea74-1970-4ddb-af4f-9a839042e21a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerLeft"",
                    ""type"": ""Button"",
                    ""id"": ""ad32f23a-1200-4a3a-b925-604f1bd00ca6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerRight"",
                    ""type"": ""Button"",
                    ""id"": ""1dd97957-271f-489e-b67c-586197fa9e10"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0b04ead0-c42b-4d5f-89ca-371aca46165f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""073dba38-7292-4c46-832a-a77af5360daa"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50993254-3510-4f56-83b7-f0df043587bf"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""339ce29d-1764-4fd9-9177-8c416de60595"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1c37932-a145-479f-9864-3a1bc43bcaa8"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7a1230f-1717-4055-bbed-7bdd9f23ee66"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f29d9b1-1fe3-4886-a426-b053916616e0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88f34497-3ce2-4fb7-afb3-a4fed3272567"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShoulderRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64293303-4c20-4313-9143-3b0c4767d8fd"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShoulderRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c028d3c4-f5b9-4822-bf7d-e9e689cb0c3f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa720480-de8a-486f-90d5-256d06236281"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d90a01dc-1dab-43d6-80c5-d7d3d66a71a1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ButtonEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee1e9a82-c8b8-4bc5-ab2b-0fd1c862a879"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f142da81-8875-4103-982d-f1bede149e95"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""89d1e898-0480-40b3-b256-87374d875a61"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c561a7c9-aaa8-42ca-b16e-b0f29d7e25f1"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db9d7a41-941c-4dcc-b10d-9dbcaafc4336"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e451b109-77b8-4216-8365-8a844a3b23b0"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfcf399e-897e-40fe-bc46-158b49d0341f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8becb381-2c28-4468-ac3d-ff5f68ac2cce"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66fa2b99-f732-4489-a5e9-1cf0ec65f4a2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43f59fff-e19f-4c2b-866d-4b3b3649ef27"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArrowUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81928748-fa33-41ff-b7a3-eac193c48328"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickButtonRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6202e3b-fe73-4a27-9f89-fc05607999c9"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickButtonLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6d21a2c-47da-4981-86bc-269e1a54e277"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShoulderLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29aafeed-85e5-4f1f-8c97-6f891c4aa6ed"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShoulderLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a256543-0620-465e-95ec-f226e9ac91cd"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Right"",
            ""id"": ""535f8663-57ae-4ab7-9f2c-e013ae0a1e69"",
            ""actions"": [
                {
                    ""name"": ""Stick"",
                    ""type"": ""Value"",
                    ""id"": ""faf108d2-3d86-4d43-bc89-ffee39a72143"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StickButton"",
                    ""type"": ""Button"",
                    ""id"": ""c05c2f91-a561-4cd7-8a0c-1a0fc31565f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""1d2961b5-048f-488c-b03f-a5a4556d7438"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""5ce96624-34cb-4b46-83a8-a2ea678b854f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""b1fb5b9f-2197-4631-ae7d-4b5aacd22b38"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""8241f2f7-1cc9-425c-8c7e-30da62ceba08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoulder"",
                    ""type"": ""Button"",
                    ""id"": ""44df284c-2033-4dee-96d2-c9bc651814b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""bb1b77ca-9a91-4d04-8bc0-69e1fa0392e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a982bb7d-2392-44bf-b4d8-01f62d745047"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45928ca9-ddea-4f6d-88be-0c6b505224e4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0c0da33-295b-4e80-898e-91b734b7f69f"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""870f5aae-852c-4d0a-b5d2-b15952b6aa70"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f978d7d5-c4ff-4cb3-93f0-f055f72bcc01"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""462102f8-734a-4224-8544-1ceba0b7bdde"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4d59b16-cea2-4a32-a68d-c3910cd580f2"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c02aa304-dfcd-4292-af61-eb33e623b4f0"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95958411-53d3-42f8-b62e-d6df39fb88e7"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3077ceb-8616-4d8d-9cbe-315726a7a89a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85498739-7589-40df-a2ca-921fffa5daf0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab839590-ae49-4090-82ee-2add09adc4a1"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37a7fcfe-b3f3-44d6-8d52-c70e207997f7"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2f96bd2a-b235-416b-89dc-b6e44fc8689b"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Left"",
            ""id"": ""318ecf8f-9337-4152-9abf-99e7ba73514e"",
            ""actions"": [
                {
                    ""name"": ""Stick"",
                    ""type"": ""Value"",
                    ""id"": ""546a9efe-97d9-49c5-aa1a-bbb6f7fdeedd"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""StickButton"",
                    ""type"": ""Button"",
                    ""id"": ""36e0ca65-9ca0-40d2-b31f-b664f066922e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""32674c3a-3b51-481a-b095-8772fe50be53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""06d05344-c607-4fab-9b0e-8615d3bd747d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Right"",
                    ""type"": ""Button"",
                    ""id"": ""aae6d674-afdd-4a38-87f9-3c2ebf2462ef"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Left"",
                    ""type"": ""Button"",
                    ""id"": ""6e9b48d4-be0f-473c-b7e7-c68086df7e8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoulder"",
                    ""type"": ""Button"",
                    ""id"": ""2e0c6e2f-d4c9-4d6e-be5e-ae43751637de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""73dbe134-a91c-4ce7-bb5c-fae528a6d49d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c142addc-b2c1-4f80-ab1c-3ae749b27e38"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fad02cf6-e574-4000-8536-d30c2dc4c5ae"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b96f9e6c-6723-4e2c-8a66-d3db24c88578"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47dff139-da1a-44e2-a539-20c9f5c307c3"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47e4fcbb-99b1-4559-83d8-11cd74019065"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d057b6f6-3cfd-4730-9d01-1cafaabb8a43"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""684d3ebc-0d1a-4ffc-84c6-4eb3d8c5c103"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21897edd-caf6-4f6e-8d99-462f34b633c3"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bad2b668-a8a3-4ec1-a235-7bedcd393a9b"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e16e9bf-d6bf-42e7-ba01-63b95c4b9752"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""387163e4-7569-4e22-818f-466909a7e9cf"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""180e205f-fadb-4bcc-92ab-57e2bad8188e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb029208-3314-41fe-9bce-f1c97937610f"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_StickRight = m_Player.FindAction("StickRight", throwIfNotFound: true);
        m_Player_StickLeft = m_Player.FindAction("StickLeft", throwIfNotFound: true);
        m_Player_StickButtonRight = m_Player.FindAction("StickButtonRight", throwIfNotFound: true);
        m_Player_StickButtonLeft = m_Player.FindAction("StickButtonLeft", throwIfNotFound: true);
        m_Player_ArrowUp = m_Player.FindAction("ArrowUp", throwIfNotFound: true);
        m_Player_ArrowDown = m_Player.FindAction("ArrowDown", throwIfNotFound: true);
        m_Player_ArrowLeft = m_Player.FindAction("ArrowLeft", throwIfNotFound: true);
        m_Player_ArrowRight = m_Player.FindAction("ArrowRight", throwIfNotFound: true);
        m_Player_ButtonNorth = m_Player.FindAction("ButtonNorth", throwIfNotFound: true);
        m_Player_ButtonSouth = m_Player.FindAction("ButtonSouth", throwIfNotFound: true);
        m_Player_ButtonEast = m_Player.FindAction("ButtonEast", throwIfNotFound: true);
        m_Player_ButtonWest = m_Player.FindAction("ButtonWest", throwIfNotFound: true);
        m_Player_ShoulderLeft = m_Player.FindAction("ShoulderLeft", throwIfNotFound: true);
        m_Player_ShoulderRight = m_Player.FindAction("ShoulderRight", throwIfNotFound: true);
        m_Player_TriggerLeft = m_Player.FindAction("TriggerLeft", throwIfNotFound: true);
        m_Player_TriggerRight = m_Player.FindAction("TriggerRight", throwIfNotFound: true);
        // Right
        m_Right = asset.FindActionMap("Right", throwIfNotFound: true);
        m_Right_Stick = m_Right.FindAction("Stick", throwIfNotFound: true);
        m_Right_StickButton = m_Right.FindAction("StickButton", throwIfNotFound: true);
        m_Right_Up = m_Right.FindAction("Up", throwIfNotFound: true);
        m_Right_Down = m_Right.FindAction("Down", throwIfNotFound: true);
        m_Right_Right = m_Right.FindAction("Right", throwIfNotFound: true);
        m_Right_Left = m_Right.FindAction("Left", throwIfNotFound: true);
        m_Right_Shoulder = m_Right.FindAction("Shoulder", throwIfNotFound: true);
        m_Right_Trigger = m_Right.FindAction("Trigger", throwIfNotFound: true);
        // Left
        m_Left = asset.FindActionMap("Left", throwIfNotFound: true);
        m_Left_Stick = m_Left.FindAction("Stick", throwIfNotFound: true);
        m_Left_StickButton = m_Left.FindAction("StickButton", throwIfNotFound: true);
        m_Left_Up = m_Left.FindAction("Up", throwIfNotFound: true);
        m_Left_Down = m_Left.FindAction("Down", throwIfNotFound: true);
        m_Left_Right = m_Left.FindAction("Right", throwIfNotFound: true);
        m_Left_Left = m_Left.FindAction("Left", throwIfNotFound: true);
        m_Left_Shoulder = m_Left.FindAction("Shoulder", throwIfNotFound: true);
        m_Left_Trigger = m_Left.FindAction("Trigger", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_StickRight;
    private readonly InputAction m_Player_StickLeft;
    private readonly InputAction m_Player_StickButtonRight;
    private readonly InputAction m_Player_StickButtonLeft;
    private readonly InputAction m_Player_ArrowUp;
    private readonly InputAction m_Player_ArrowDown;
    private readonly InputAction m_Player_ArrowLeft;
    private readonly InputAction m_Player_ArrowRight;
    private readonly InputAction m_Player_ButtonNorth;
    private readonly InputAction m_Player_ButtonSouth;
    private readonly InputAction m_Player_ButtonEast;
    private readonly InputAction m_Player_ButtonWest;
    private readonly InputAction m_Player_ShoulderLeft;
    private readonly InputAction m_Player_ShoulderRight;
    private readonly InputAction m_Player_TriggerLeft;
    private readonly InputAction m_Player_TriggerRight;
    public struct PlayerActions
    {
        private @BasicControls m_Wrapper;
        public PlayerActions(@BasicControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @StickRight => m_Wrapper.m_Player_StickRight;
        public InputAction @StickLeft => m_Wrapper.m_Player_StickLeft;
        public InputAction @StickButtonRight => m_Wrapper.m_Player_StickButtonRight;
        public InputAction @StickButtonLeft => m_Wrapper.m_Player_StickButtonLeft;
        public InputAction @ArrowUp => m_Wrapper.m_Player_ArrowUp;
        public InputAction @ArrowDown => m_Wrapper.m_Player_ArrowDown;
        public InputAction @ArrowLeft => m_Wrapper.m_Player_ArrowLeft;
        public InputAction @ArrowRight => m_Wrapper.m_Player_ArrowRight;
        public InputAction @ButtonNorth => m_Wrapper.m_Player_ButtonNorth;
        public InputAction @ButtonSouth => m_Wrapper.m_Player_ButtonSouth;
        public InputAction @ButtonEast => m_Wrapper.m_Player_ButtonEast;
        public InputAction @ButtonWest => m_Wrapper.m_Player_ButtonWest;
        public InputAction @ShoulderLeft => m_Wrapper.m_Player_ShoulderLeft;
        public InputAction @ShoulderRight => m_Wrapper.m_Player_ShoulderRight;
        public InputAction @TriggerLeft => m_Wrapper.m_Player_TriggerLeft;
        public InputAction @TriggerRight => m_Wrapper.m_Player_TriggerRight;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @StickRight.started += instance.OnStickRight;
            @StickRight.performed += instance.OnStickRight;
            @StickRight.canceled += instance.OnStickRight;
            @StickLeft.started += instance.OnStickLeft;
            @StickLeft.performed += instance.OnStickLeft;
            @StickLeft.canceled += instance.OnStickLeft;
            @StickButtonRight.started += instance.OnStickButtonRight;
            @StickButtonRight.performed += instance.OnStickButtonRight;
            @StickButtonRight.canceled += instance.OnStickButtonRight;
            @StickButtonLeft.started += instance.OnStickButtonLeft;
            @StickButtonLeft.performed += instance.OnStickButtonLeft;
            @StickButtonLeft.canceled += instance.OnStickButtonLeft;
            @ArrowUp.started += instance.OnArrowUp;
            @ArrowUp.performed += instance.OnArrowUp;
            @ArrowUp.canceled += instance.OnArrowUp;
            @ArrowDown.started += instance.OnArrowDown;
            @ArrowDown.performed += instance.OnArrowDown;
            @ArrowDown.canceled += instance.OnArrowDown;
            @ArrowLeft.started += instance.OnArrowLeft;
            @ArrowLeft.performed += instance.OnArrowLeft;
            @ArrowLeft.canceled += instance.OnArrowLeft;
            @ArrowRight.started += instance.OnArrowRight;
            @ArrowRight.performed += instance.OnArrowRight;
            @ArrowRight.canceled += instance.OnArrowRight;
            @ButtonNorth.started += instance.OnButtonNorth;
            @ButtonNorth.performed += instance.OnButtonNorth;
            @ButtonNorth.canceled += instance.OnButtonNorth;
            @ButtonSouth.started += instance.OnButtonSouth;
            @ButtonSouth.performed += instance.OnButtonSouth;
            @ButtonSouth.canceled += instance.OnButtonSouth;
            @ButtonEast.started += instance.OnButtonEast;
            @ButtonEast.performed += instance.OnButtonEast;
            @ButtonEast.canceled += instance.OnButtonEast;
            @ButtonWest.started += instance.OnButtonWest;
            @ButtonWest.performed += instance.OnButtonWest;
            @ButtonWest.canceled += instance.OnButtonWest;
            @ShoulderLeft.started += instance.OnShoulderLeft;
            @ShoulderLeft.performed += instance.OnShoulderLeft;
            @ShoulderLeft.canceled += instance.OnShoulderLeft;
            @ShoulderRight.started += instance.OnShoulderRight;
            @ShoulderRight.performed += instance.OnShoulderRight;
            @ShoulderRight.canceled += instance.OnShoulderRight;
            @TriggerLeft.started += instance.OnTriggerLeft;
            @TriggerLeft.performed += instance.OnTriggerLeft;
            @TriggerLeft.canceled += instance.OnTriggerLeft;
            @TriggerRight.started += instance.OnTriggerRight;
            @TriggerRight.performed += instance.OnTriggerRight;
            @TriggerRight.canceled += instance.OnTriggerRight;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @StickRight.started -= instance.OnStickRight;
            @StickRight.performed -= instance.OnStickRight;
            @StickRight.canceled -= instance.OnStickRight;
            @StickLeft.started -= instance.OnStickLeft;
            @StickLeft.performed -= instance.OnStickLeft;
            @StickLeft.canceled -= instance.OnStickLeft;
            @StickButtonRight.started -= instance.OnStickButtonRight;
            @StickButtonRight.performed -= instance.OnStickButtonRight;
            @StickButtonRight.canceled -= instance.OnStickButtonRight;
            @StickButtonLeft.started -= instance.OnStickButtonLeft;
            @StickButtonLeft.performed -= instance.OnStickButtonLeft;
            @StickButtonLeft.canceled -= instance.OnStickButtonLeft;
            @ArrowUp.started -= instance.OnArrowUp;
            @ArrowUp.performed -= instance.OnArrowUp;
            @ArrowUp.canceled -= instance.OnArrowUp;
            @ArrowDown.started -= instance.OnArrowDown;
            @ArrowDown.performed -= instance.OnArrowDown;
            @ArrowDown.canceled -= instance.OnArrowDown;
            @ArrowLeft.started -= instance.OnArrowLeft;
            @ArrowLeft.performed -= instance.OnArrowLeft;
            @ArrowLeft.canceled -= instance.OnArrowLeft;
            @ArrowRight.started -= instance.OnArrowRight;
            @ArrowRight.performed -= instance.OnArrowRight;
            @ArrowRight.canceled -= instance.OnArrowRight;
            @ButtonNorth.started -= instance.OnButtonNorth;
            @ButtonNorth.performed -= instance.OnButtonNorth;
            @ButtonNorth.canceled -= instance.OnButtonNorth;
            @ButtonSouth.started -= instance.OnButtonSouth;
            @ButtonSouth.performed -= instance.OnButtonSouth;
            @ButtonSouth.canceled -= instance.OnButtonSouth;
            @ButtonEast.started -= instance.OnButtonEast;
            @ButtonEast.performed -= instance.OnButtonEast;
            @ButtonEast.canceled -= instance.OnButtonEast;
            @ButtonWest.started -= instance.OnButtonWest;
            @ButtonWest.performed -= instance.OnButtonWest;
            @ButtonWest.canceled -= instance.OnButtonWest;
            @ShoulderLeft.started -= instance.OnShoulderLeft;
            @ShoulderLeft.performed -= instance.OnShoulderLeft;
            @ShoulderLeft.canceled -= instance.OnShoulderLeft;
            @ShoulderRight.started -= instance.OnShoulderRight;
            @ShoulderRight.performed -= instance.OnShoulderRight;
            @ShoulderRight.canceled -= instance.OnShoulderRight;
            @TriggerLeft.started -= instance.OnTriggerLeft;
            @TriggerLeft.performed -= instance.OnTriggerLeft;
            @TriggerLeft.canceled -= instance.OnTriggerLeft;
            @TriggerRight.started -= instance.OnTriggerRight;
            @TriggerRight.performed -= instance.OnTriggerRight;
            @TriggerRight.canceled -= instance.OnTriggerRight;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Right
    private readonly InputActionMap m_Right;
    private List<IRightActions> m_RightActionsCallbackInterfaces = new List<IRightActions>();
    private readonly InputAction m_Right_Stick;
    private readonly InputAction m_Right_StickButton;
    private readonly InputAction m_Right_Up;
    private readonly InputAction m_Right_Down;
    private readonly InputAction m_Right_Right;
    private readonly InputAction m_Right_Left;
    private readonly InputAction m_Right_Shoulder;
    private readonly InputAction m_Right_Trigger;
    public struct RightActions
    {
        private @BasicControls m_Wrapper;
        public RightActions(@BasicControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Stick => m_Wrapper.m_Right_Stick;
        public InputAction @StickButton => m_Wrapper.m_Right_StickButton;
        public InputAction @Up => m_Wrapper.m_Right_Up;
        public InputAction @Down => m_Wrapper.m_Right_Down;
        public InputAction @Right => m_Wrapper.m_Right_Right;
        public InputAction @Left => m_Wrapper.m_Right_Left;
        public InputAction @Shoulder => m_Wrapper.m_Right_Shoulder;
        public InputAction @Trigger => m_Wrapper.m_Right_Trigger;
        public InputActionMap Get() { return m_Wrapper.m_Right; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RightActions set) { return set.Get(); }
        public void AddCallbacks(IRightActions instance)
        {
            if (instance == null || m_Wrapper.m_RightActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RightActionsCallbackInterfaces.Add(instance);
            @Stick.started += instance.OnStick;
            @Stick.performed += instance.OnStick;
            @Stick.canceled += instance.OnStick;
            @StickButton.started += instance.OnStickButton;
            @StickButton.performed += instance.OnStickButton;
            @StickButton.canceled += instance.OnStickButton;
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Shoulder.started += instance.OnShoulder;
            @Shoulder.performed += instance.OnShoulder;
            @Shoulder.canceled += instance.OnShoulder;
            @Trigger.started += instance.OnTrigger;
            @Trigger.performed += instance.OnTrigger;
            @Trigger.canceled += instance.OnTrigger;
        }

        private void UnregisterCallbacks(IRightActions instance)
        {
            @Stick.started -= instance.OnStick;
            @Stick.performed -= instance.OnStick;
            @Stick.canceled -= instance.OnStick;
            @StickButton.started -= instance.OnStickButton;
            @StickButton.performed -= instance.OnStickButton;
            @StickButton.canceled -= instance.OnStickButton;
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Shoulder.started -= instance.OnShoulder;
            @Shoulder.performed -= instance.OnShoulder;
            @Shoulder.canceled -= instance.OnShoulder;
            @Trigger.started -= instance.OnTrigger;
            @Trigger.performed -= instance.OnTrigger;
            @Trigger.canceled -= instance.OnTrigger;
        }

        public void RemoveCallbacks(IRightActions instance)
        {
            if (m_Wrapper.m_RightActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRightActions instance)
        {
            foreach (var item in m_Wrapper.m_RightActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RightActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RightActions @Right => new RightActions(this);

    // Left
    private readonly InputActionMap m_Left;
    private List<ILeftActions> m_LeftActionsCallbackInterfaces = new List<ILeftActions>();
    private readonly InputAction m_Left_Stick;
    private readonly InputAction m_Left_StickButton;
    private readonly InputAction m_Left_Up;
    private readonly InputAction m_Left_Down;
    private readonly InputAction m_Left_Right;
    private readonly InputAction m_Left_Left;
    private readonly InputAction m_Left_Shoulder;
    private readonly InputAction m_Left_Trigger;
    public struct LeftActions
    {
        private @BasicControls m_Wrapper;
        public LeftActions(@BasicControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Stick => m_Wrapper.m_Left_Stick;
        public InputAction @StickButton => m_Wrapper.m_Left_StickButton;
        public InputAction @Up => m_Wrapper.m_Left_Up;
        public InputAction @Down => m_Wrapper.m_Left_Down;
        public InputAction @Right => m_Wrapper.m_Left_Right;
        public InputAction @Left => m_Wrapper.m_Left_Left;
        public InputAction @Shoulder => m_Wrapper.m_Left_Shoulder;
        public InputAction @Trigger => m_Wrapper.m_Left_Trigger;
        public InputActionMap Get() { return m_Wrapper.m_Left; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LeftActions set) { return set.Get(); }
        public void AddCallbacks(ILeftActions instance)
        {
            if (instance == null || m_Wrapper.m_LeftActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LeftActionsCallbackInterfaces.Add(instance);
            @Stick.started += instance.OnStick;
            @Stick.performed += instance.OnStick;
            @Stick.canceled += instance.OnStick;
            @StickButton.started += instance.OnStickButton;
            @StickButton.performed += instance.OnStickButton;
            @StickButton.canceled += instance.OnStickButton;
            @Up.started += instance.OnUp;
            @Up.performed += instance.OnUp;
            @Up.canceled += instance.OnUp;
            @Down.started += instance.OnDown;
            @Down.performed += instance.OnDown;
            @Down.canceled += instance.OnDown;
            @Right.started += instance.OnRight;
            @Right.performed += instance.OnRight;
            @Right.canceled += instance.OnRight;
            @Left.started += instance.OnLeft;
            @Left.performed += instance.OnLeft;
            @Left.canceled += instance.OnLeft;
            @Shoulder.started += instance.OnShoulder;
            @Shoulder.performed += instance.OnShoulder;
            @Shoulder.canceled += instance.OnShoulder;
            @Trigger.started += instance.OnTrigger;
            @Trigger.performed += instance.OnTrigger;
            @Trigger.canceled += instance.OnTrigger;
        }

        private void UnregisterCallbacks(ILeftActions instance)
        {
            @Stick.started -= instance.OnStick;
            @Stick.performed -= instance.OnStick;
            @Stick.canceled -= instance.OnStick;
            @StickButton.started -= instance.OnStickButton;
            @StickButton.performed -= instance.OnStickButton;
            @StickButton.canceled -= instance.OnStickButton;
            @Up.started -= instance.OnUp;
            @Up.performed -= instance.OnUp;
            @Up.canceled -= instance.OnUp;
            @Down.started -= instance.OnDown;
            @Down.performed -= instance.OnDown;
            @Down.canceled -= instance.OnDown;
            @Right.started -= instance.OnRight;
            @Right.performed -= instance.OnRight;
            @Right.canceled -= instance.OnRight;
            @Left.started -= instance.OnLeft;
            @Left.performed -= instance.OnLeft;
            @Left.canceled -= instance.OnLeft;
            @Shoulder.started -= instance.OnShoulder;
            @Shoulder.performed -= instance.OnShoulder;
            @Shoulder.canceled -= instance.OnShoulder;
            @Trigger.started -= instance.OnTrigger;
            @Trigger.performed -= instance.OnTrigger;
            @Trigger.canceled -= instance.OnTrigger;
        }

        public void RemoveCallbacks(ILeftActions instance)
        {
            if (m_Wrapper.m_LeftActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILeftActions instance)
        {
            foreach (var item in m_Wrapper.m_LeftActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LeftActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LeftActions @Left => new LeftActions(this);
    public interface IPlayerActions
    {
        void OnStickRight(InputAction.CallbackContext context);
        void OnStickLeft(InputAction.CallbackContext context);
        void OnStickButtonRight(InputAction.CallbackContext context);
        void OnStickButtonLeft(InputAction.CallbackContext context);
        void OnArrowUp(InputAction.CallbackContext context);
        void OnArrowDown(InputAction.CallbackContext context);
        void OnArrowLeft(InputAction.CallbackContext context);
        void OnArrowRight(InputAction.CallbackContext context);
        void OnButtonNorth(InputAction.CallbackContext context);
        void OnButtonSouth(InputAction.CallbackContext context);
        void OnButtonEast(InputAction.CallbackContext context);
        void OnButtonWest(InputAction.CallbackContext context);
        void OnShoulderLeft(InputAction.CallbackContext context);
        void OnShoulderRight(InputAction.CallbackContext context);
        void OnTriggerLeft(InputAction.CallbackContext context);
        void OnTriggerRight(InputAction.CallbackContext context);
    }
    public interface IRightActions
    {
        void OnStick(InputAction.CallbackContext context);
        void OnStickButton(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnShoulder(InputAction.CallbackContext context);
        void OnTrigger(InputAction.CallbackContext context);
    }
    public interface ILeftActions
    {
        void OnStick(InputAction.CallbackContext context);
        void OnStickButton(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnRight(InputAction.CallbackContext context);
        void OnLeft(InputAction.CallbackContext context);
        void OnShoulder(InputAction.CallbackContext context);
        void OnTrigger(InputAction.CallbackContext context);
    }
}
